# Generated by Django 2.2 on 2019-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190526_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text='Enter phone number of client', max_length=19),
        ),
    ]
