# Generated by Django 2.2 on 2019-06-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190601_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
