# Generated by Django 2.2 on 2019-06-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_request_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-status']},
        ),
    ]
