# Generated by Django 2.2 on 2019-06-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190602_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='data',
            field=models.DateField(),
        ),
    ]
