# Generated by Django 2.2 on 2019-06-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20190602_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-data', '-status', 'id')},
        ),
    ]
